config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
  resources :users, only: [:edit, :update,:index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :group_members
  has_many :users, through: :group_members
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :user
  belongs_to :group

end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :group
  validates :content, presence: true, unless: :image?
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :messages
  has_many :group_members
  has_many :groups, through: :group_members

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController

 def index
  
  @group = Group.find(params[:group_id])
  @messages = @group.messages.includes(:user).where('id > ?',params[:last_id])
  respond_to do |format|
    format.html
    format.json
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end


  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
   
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end


  private
  def group_params
    params.require(:group).permit(:name, { user_ids: []})
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_group
  
    def index
      @message = Message.new
      @messages = @group.messages.includes(:user)
      @members = @group.users
    end
  
    def create
      @message = @group.messages.new(message_params)
      @message.user_id = current_user.id  

      if @message.save
        respond_to do |format|
          format.html 
            # {redirect_to group_messages_path(@group), notice: 'メッセージが送信されました}'
          format.json 
        end
      else
        @messages = @group.messages.includes(:user)
        flash.now[:alert] = 'メッセージを入力してください。'
        render :index
      end
    end
  
    private
  
    def message_params
      params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
      # params.require(:message).permit(:content ,:image, :user_id).merge(group_id: params[:group_id])
    end
  
    def set_group
      @group = Group.find(params[:group_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where.not(id: current_user.id).where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
    format.json
    end   
  end


  def edit
  end
  
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  -if @group.errors.any? 
    
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message
      
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name , class: 'chat-group-form__label'
    
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  
  .chat-group-form__field.clearfix

    .chat-group-form__field--left
      %label.chat-group-form__label{for:  "menbers"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #user-search-result
  
  
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "menbers"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users.js-add-user
        - @group.users.each do |user|
          #chat-group-user-8.chat-group-user.clearfix.js-chat-member
            %input{:name => "group[user_ids][]", :type => "hidden", :value => "#{ user.id }"}/
            %p.chat-group-user__name
              = user.name
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除
      

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'
      

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.contents
  = render 'messages/left-content' 

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_flash.html.haml
.flash
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_group-content.html.haml
.group-content
  - current_user.groups.each do |group|
    = link_to group_messages_path(group) do
      .group-content__name
        = group.name
      .group-content__message
        = group.show_last_message

app/views/messages/_left-content.html.haml
.left-content
  .left-content__header
    .left-content__header__box
      %p.left-content__header__box__user-name
        =current_user.name
      %ul.left-content__header__box__menu
        %li.left-content__header__box__menu__new-group
          =link_to new_group_path, class: "fa" do
            = fa_icon 'edit'
        %li.left-content__header__box__menu__edit-user
          =link_to edit_user_path(current_user), class: "fa" do
            = fa_icon 'cog'
  .left-content__group-content
    = render partial: 'messages/group-content'
    
  -# 左側コンテンツ
  

app/views/messages/_message.html.haml
.right-content__main__box{data: {id: message.id}}
  .right-content__main__box__name
    = message.user.name
  .right-content__main__box__timestamp
    = message.created_at.strftime("%Y/%m/%d %H:%M")
.right-content__main__message
  - if message.content.present?
    %p.lower-message__content
      = message.content
  = image_tag message.image, class: 'lower-message__image' if message.image.present?
  

app/views/messages/_right-content.html.haml
.right-content
  .right-content__header
    .right-content__header__groupe
      %p.right-content__header__groupe__name #{@group.name}
      %p.right-content__header__groupe__members Menber:
      %p.right-content__header__groupe__members
        - @members.each do |member|
          =member.name	       
        
            
    .right-content__header__edit_button
      =link_to 'Edit',  edit_group_path(params[:group_id]), method: :get
        
  

  .right-content__main
    = render @messages
    
  
  .right-content__footer
    = form_for [@group, @message] do |f|
      = f.text_field :content, class: 'right-content__footer__text', placeholder: 'type a message'
      .right-content__footer__form__mask
        = f.label :image, class: 'form__mask__image' do
          = fa_icon 'picture-o ' , class: 'icon'
          = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: 'right-content__footer__send-button'

app/views/messages/index.html.haml
.contents
  = render partial: 'left-content'           
  -# 左側コンテンツ
  
  = render partial:'right-content'
  -# 右側コンテンツ 

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'